### ISSUE TITLE
[FEATURE REQUEST] Function to return a secret, if it doesn't exist generate a random string, set it, and return it.

### ISSUE THREAD

**Issue by tazaki** [salt-extensions/saltext-vault#38]
I wasn't sure where the best place for this discussion so figured I would just make a ticket.

**Is your feature request related to a problem? Please describe.**
A common use case we have is to initialize new clusters of applications that need secrets generated. We don't care what the secrets are as long as they are unique per environment. The way we have been doing this is with a custom execution module in salt called get_set_secret. 

**Describe the solution you'd like**
vault.get_set_secret

This function has two arguments:
* Path to a secret you want to read or write to
* Dictionary of key values you want to generate if the secret doesn't exist. 
* If the value of one of the keys is something like "generate" we just generate a random string of say 30 characters and use that. Could add additional arguments to change this behavior. 

**Describe alternatives you've considered**
Before using this method we would manually bootstrap and load secrets into our new clusters each time we redeployed. 

**Additional context**
The main downside I see with this is salt needing write permissions to the paths would could be considered a security issue. 

I am interested in any other approaches or advice as well!

**Comment by lkubb** [comment]
> We don't care what the secrets are as long as they are unique per environment.

Do you know about `sdb.get_or_set_hash`, which works with the `vault` SDB module? It takes a
> Path to a secret you want to read or write to

\+ a length and charset of the secret to generate if it does not exist at the path. It does not however generate multiple values per invocation.

> The main downside I see with this is salt needing write permissions to the paths would could be considered a security issue.

Agreed, there's some potential for lateral movement, but you might be able to mitigate it somewhat by only allowing the creation of the secret, no updates. For multiple values, this would require one (Vault) path per secret though.

**Comment by tazaki** [comment]
> Do you know about [sdb.get_or_set_hash](https://docs.saltproject.io/en/latest/ref/modules/all/salt.modules.sdb.html#salt.modules.sdb.get_or_set_hash), which works with the `vault` SDB module? It takes a
> 
> > Path to a secret you want to read or write to
> 
> + a length and charset of the secret to generate if it does not exist at the path. It does not however generate multiple values per invocation.
> 

Oh no I did not know this. What is the reason to use vault with sdb vs just calling the execution module in the state?

**Comment by lkubb** [comment]
It's just a different interface to the same backend, but it provides a similar function to the one you describe, no other reason. You can use both methods at the same time.

In general, you can specify SDB URI in places where `config.get` is used to transparently source (configuration) values from databases instead of writing them to the config in plain text. You can read about it [in the Salt docs](https://docs.saltproject.io/en/latest/topics/sdb/index.html).

**Comment by tazaki** [comment]
Ok thank you. I will give this a try!
