### ISSUE TITLE
[BUG] Client configuration is sometimes not respected when unwrapping credentials

### ISSUE THREAD

**Issue by callanova** [salt-extensions/saltext-vault#95]
**Edit by maintainer**
This issue turned out to have two independent causes, setup problems (wrong version of the modules + missing `retry_post: true`) and the following bug:

When a minion needs to request new configuration, the client it uses to unwrap the token/RoleID/SecretID does not respect the `client` configuration from the master. This does not happen when cached configuration is available.

The original issue description follows below.

**Description**

It's unclear if the retry_status is being respected and prompting salt-minions to retry based on status codes received.

In the vault.conf, we set the following:
```
peer_run:
  .*:
    - vault.get_config
    - vault.generate_secret_id
    - vault.read_secret

vault:
  auth:
    method: approle
    approle_mount: salt-minions
    approle_name: salt_master
    role_id: $REPLACEME
    secret_id: $REPLACEME
  issue:
    type: approle
    approle:
      mount: salt-minions
      params:
        token_num_uses: 0
        token_type: batch
  server:
    url: https://vault.company.com
    namespace: admin/
  client:
    max_retries: 10
    backoff_factor: 2.0
    retry_status:
      - 412
      - 500
      - 502
      - 503
      - 504
```
We have a state file similar to this:
```
{% set data = salt['vault.read_secret']('secrets/data/automation/saltstack/testing/ubuntu/data') %}
create_file:
  file.managed:
    - name: /home/ubuntu/test.txt
    - source: salt://dir/files/test.txt
    - template: jinja
    - context:
        data: "{{ data }}"
    - user: ubuntu
    - group: ubuntu
    - mode: 644
```
Randomly during automated state file application, we can run into this message:
```
Rendering SLS 'base:dir.file' failed: Problem running salt function in Jinja template: Failed to read secret! VaultServerError: error performing token check: no lease entry found for token that ought to have one, possible eventual consistency issue
```
If I turn on debugging, I can see the following:
```
2024-11-04 10:06:12,818 [urllib3.connectionpool:1019][DEBUG   ][3136127] Starting new HTTPS connection (1): vault.company.com:443
2024-11-04 10:06:12,962 [urllib3.connectionpool:474 ][DEBUG   ][3136127] https://vault.company.com:443 "POST /v1/sys/wrapping/unwrap HTTP/1.1" 200 230
2024-11-04 10:06:12,963 [salt.utils.vault.factory:573 ][DEBUG   ][3136127] Using secret_id issued by master.
2024-11-04 10:06:12,963 [salt.utils.vault.factory:527 ][DEBUG   ][3136127] Fetching new Vault AppRole secret ID.
2024-11-04 10:06:12,963 [salt.utils.vault.factory:788 ][DEBUG   ][3136127] Running on minion, signing request `vault.generate_secret_id` with key /etc/salt/pki/minion/minion.pem
2024-11-04 10:06:12,963 [salt.crypt       :306 ][DEBUG   ][3136127] salt.crypt.get_rsa_key: Loading private key
2024-11-04 10:06:12,963 [salt.crypt       :337 ][DEBUG   ][3136127] salt.crypt.sign_message: Signing message.
2024-11-04 10:06:12,965 [salt.modules.publish:334 ][INFO    ][3136127] Publishing runner 'vault.generate_secret_id' to tcp://10.151.126.12:4506
2024-11-04 10:06:12,965 [salt.crypt       :1436][DEBUG   ][3136127] Initializing new SAuth for ('/etc/salt/pki/minion', 'salt-minion', 'tcp://10.151.126.12:4506')
2024-11-04 10:06:12,965 [salt.crypt       :306 ][DEBUG   ][3136127] salt.crypt.get_rsa_key: Loading private key
2024-11-04 10:06:12,965 [salt.crypt       :1082][DEBUG   ][3136127] Loaded minion key: /etc/salt/pki/minion/minion.pem
2024-11-04 10:06:12,972 [asyncio          :54  ][DEBUG   ][3136127] Using selector: EpollSelector
2024-11-04 10:06:12,972 [salt.crypt       :690 ][DEBUG   ][3136127] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'salt-minion', 'tcp://10.151.126.12:4506')
2024-11-04 10:06:13,689 [salt.channel.client:359 ][DEBUG   ][3136127] Closing AsyncReqChannel instance
2024-11-04 10:06:13,705 [urllib3.connectionpool:474 ][DEBUG   ][3136127] https://vault.company.com:443 "POST /v1/sys/wrapping/lookup HTTP/1.1" 500 136
2024-11-04 10:06:13,707 [salt.utils.templates:223 ][ERROR   ][3136127] Rendering exception occurred
2024-11-04 10:06:13,708 [salt.state       :4369][CRITICAL][3136127] Rendering SLS 'base:dir.file' failed: Problem running salt function in Jinja template: Failed to read secret! VaultServerError: error performing token check: no lease entry found for token that ought to have one, possible eventual consistency issue; line 4
```
When I compare it to a successful application, the `POST /v1/sys/wrapping/lookup` is a 200 instead of 500 and everything works as expected:
```
2024-11-04 10:35:28,961 [urllib3.connectionpool:1019][DEBUG   ][412832] Starting new HTTPS connection (1): vault.company.com:443
2024-11-04 10:35:29,085 [urllib3.connectionpool:474 ][DEBUG   ][412832] https://vault.company.com:443 "POST /v1/sys/wrapping/unwrap HTTP/1.1" 200 230
2024-11-04 10:35:29,086 [salt.utils.vault.factory:573 ][DEBUG   ][412832] Using secret_id issued by master.
2024-11-04 10:35:29,086 [salt.utils.vault.factory:527 ][DEBUG   ][412832] Fetching new Vault AppRole secret ID.
2024-11-04 10:35:29,086 [salt.utils.vault.factory:788 ][DEBUG   ][412832] Running on minion, signing request `vault.generate_secret_id` with key /etc/salt/pki/minion/minion.pem
2024-11-04 10:35:29,086 [salt.crypt       :306 ][DEBUG   ][412832] salt.crypt.get_rsa_key: Loading private key
2024-11-04 10:35:29,087 [salt.crypt       :337 ][DEBUG   ][412832] salt.crypt.sign_message: Signing message.
2024-11-04 10:35:29,088 [salt.modules.publish:334 ][INFO    ][412832] Publishing runner 'vault.generate_secret_id' to tcp://10.151.126.12:4506
2024-11-04 10:35:29,088 [salt.crypt       :1436][DEBUG   ][412832] Initializing new SAuth for ('/etc/salt/pki/minion', 'salt-minion', 'tcp://10.151.126.12:4506')
2024-11-04 10:35:29,089 [salt.crypt       :306 ][DEBUG   ][412832] salt.crypt.get_rsa_key: Loading private key
2024-11-04 10:35:29,089 [salt.crypt       :1082][DEBUG   ][412832] Loaded minion key: /etc/salt/pki/minion/minion.pem
2024-11-04 10:35:29,095 [asyncio          :54  ][DEBUG   ][412832] Using selector: EpollSelector
2024-11-04 10:35:29,096 [salt.crypt       :690 ][DEBUG   ][412832] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'salt-minion', 'tcp://10.151.126.12:4506')
2024-11-04 10:35:30,020 [salt.channel.client:359 ][DEBUG   ][412832] Closing AsyncReqChannel instance
2024-11-04 10:35:30,044 [urllib3.connectionpool:474 ][DEBUG   ][412832] https://vault.company.com:443 "POST /v1/sys/wrapping/lookup HTTP/1.1" 200 316
2024-11-04 10:35:30,143 [urllib3.connectionpool:474 ][DEBUG   ][412832] https://vault.company.com:443 "POST /v1/sys/wrapping/unwrap HTTP/1.1" 200 334
2024-11-04 10:35:30,143 [salt.utils.vault.auth:129 ][DEBUG   ][412832] Vault token expired. Recreating one by authenticating with AppRole.
2024-11-04 10:35:30,306 [urllib3.connectionpool:474 ][DEBUG   ][412832] https://vault.company.com:443 "POST /v1/auth/salt-minions/login HTTP/1.1" 200 1237
2024-11-04 10:35:30,306 [salt.utils.vault.kv:245 ][DEBUG   ][412832] Fetching metadata for secrets/data/automation/saltstack/testing/ubuntu/data'
2024-11-04 10:35:30,316 [urllib3.connectionpool:474 ][DEBUG   ][412832] https://vault.company.com:443 "GET /v1/sys/internal/ui/mounts/secrets/data/automation/saltstack/testing/ubuntu/data' HTTP/1.1" 200 588
2024-11-04 10:35:30,317 [salt.utils.vault.kv:250 ][DEBUG   ][412832] Got metadata for secrets/data/automation/saltstack/testing/ubuntu/data'
2024-11-04 10:35:30,317 [salt.utils.vault.kv:231 ][DEBUG   ][412832] Path secrets/data/automation/saltstack/testing/ubuntu/data' already contains data in the right place - saltstack duct tape?
2024-11-04 10:35:30,317 [salt.utils.vault.kv:231 ][DEBUG   ][412832] Path is a "data" type but "metadata" type requested - Flipping: secrets/metadata/automation/saltstack/testing/ubuntu/data'
2024-11-04 10:35:30,317 [salt.utils.vault.kv:231 ][DEBUG   ][412832] Path is a "data" type but "delete" type requested - Flipping: secrets/delete/automation/saltstack/testing/ubuntu/data'
2024-11-04 10:35:30,317 [salt.utils.vault.kv:231 ][DEBUG   ][412832] Path is a "data" type but "destroy" type requested - Flipping: secrets/destroy/automation/saltstack/testing/ubuntu/data'
2024-11-04 10:35:30,326 [urllib3.connectionpool:474 ][DEBUG   ][412832] https://vault.company.com:443 "GET /v1/secrets/data/automation/saltstack/testing/ubuntu/data' HTTP/1.1" 200 744
```
Based off the debugging logs, it's unclear to me if the retry is being used prior to going to the rendering exception message.
Is there something off with the vault.conf causing the retry to not trigger? Is the backoff_factor set too high?

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info. There is no general set-up of Salt.)

Please be as specific as possible and give set-up details.

- [X] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [X] classic packaging
- [ ] onedir packaging
- [ ] used bootstrap to install

/etc/salt/master.d/vault.conf:
```
peer_run:
  .*:
    - vault.get_config
    - vault.generate_secret_id
    - vault.read_secret

vault:
  auth:
    method: approle
    approle_mount: salt-minions
    approle_name: salt_master
    role_id: $REPLACEME
    secret_id: $REPLACEME
  issue:
    type: approle
    approle:
      mount: salt-minions
      params:
        token_num_uses: 0
        token_type: batch
  server:
    url: https://vault.company.com
    namespace: admin/
  client:
    max_retries: 10
    backoff_factor: 2.0
    retry_status:
      - 412
      - 500
      - 502
      - 503
      - 504
```

**Steps to Reproduce the behavior**
(Include debug logs if possible and relevant)
Difficult to reproduce on demand. It happens very randomly.
See above for debug logs from the salt-minion.

**Expected behavior**
Retry when receiving a 500 error instead of going straight to a "Rendering exception occurred" error.

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
          Salt: 3006.6

Python Version:
        Python: 3.10.12 (main, Sep 11 2024, 15:47:36) [GCC 11.4.0]

Dependency Versions:
          cffi: 1.17.1
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.0.3
       libgit2: Not Installed
  looseversion: 1.3.0
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.8
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 24.1
     pycparser: 2.22
      pycrypto: Not Installed
  pycryptodome: 3.20.0
        pygit2: Not Installed
  python-gnupg: Not Installed
        PyYAML: 5.4.1
         PyZMQ: 25.0.2
        relenv: Not Installed
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4

Salt Extensions:
 saltext.vault: 1.2.0

System Versions:
          dist: ubuntu 22.04.5 jammy
        locale: utf-8
       machine: x86_64
       release: 5.15.0-124-generic
        system: Linux
       version: Ubuntu 22.04.5 jammy
```
</details>

**Additional context**

**Comment by lkubb** [comment]
The failing request is a `POST` request, which is not retried by default (https://salt-extensions.github.io/saltext-vault/ref/configuration.html#retry-post).

I would argue that POST requests to `sys/wrapping/+` are safe to retry though, we could probably implement an API method-specific override to whitelist some methods by default.

**Comment by callanova** [comment]
I tried setting vault/client/retry_post to true:
```
vault:
  ...
  client:
    max_retries: 10
    backoff_factor: 2.0
    retry_post: true
    retry_status:
      - 412
      - 500
      - 502
      - 503
      - 504
  ...
```
I restarted the salt-master using `sudo systemctl restart salt-master`, confirmed the salt-master was running with `sudo systemctl status salt-master`. and then let everything run.
Unfortunately, it still goes from 500 to the rendering exception message.
I also tried `retry_post: True` in the config file just in case it was case sensitive.

On the random instances where the state application fails, the logs from the salt-minion still show it going straight from the 500 status code to the rendering exception message:
```
2024-11-04 22:06:24,502 [urllib3.connectionpool:474 ][DEBUG   ][2903245] https://vault.company.com:443 "POST /v1/sys/wrapping/lookup HTTP/1.1" 500 136
2024-11-04 22:06:24,503 [salt.utils.templates:223 ][ERROR   ][2903245] Rendering exception occurred
```

I initially reached out to Hashicorp about the `error performing token check` message.
They recommended switching to batch tokens due to the error.

Thanks for the note about the runner function, will get that removed.

**Comment by lkubb** [comment]
Did you refresh the cached configuration on the minion after changing it on the master? (`salt minion vault.update_config`)

**Comment by callanova** [comment]
> Did you refresh the cached configuration on the minion after changing it on the master? (salt minion vault.update_config)

After making the changes to the vault config yesterday, no.
Ran `sudo salt 'minion' vault.update_config` today and it returned true.
Unfortunately, it still went from 500 to the rendering exception message.

> Edit: Just saw your config does not define a persistent cache, is that correct?

Correct. I'm using the default.

> The following patch should fix it (off the top of my head):

On the salt-master, it looks like the file is here:
```
/usr/local/lib/python3.10/dist-packages/saltext/vault/utils/vault/factory.py
```
While on salt-minions, the file is here:
```
/opt/saltstack/salt/extras-3.10/saltext/vault/utils/vault/factory.py
```

I created a salt state to make the changes to the `/opt/saltstack/salt/extras-3.10/saltext/vault/utils/vault/factory.py` on the salt-minions.
Confirmed `retry_post: true` is still in the vault config.
I applied the state and waited for the automation to kick off.
Here's the change that was returned:
```
     Changes:
              ----------
              diff:
                  ---
                  +++
                  @@ -500,8 +500,11 @@
                           config_cache.flush(cbank=False)

                       config_cache.store(new_config)
                  -    if unwrap_client is None:
                  -        unwrap_client = vclient.VaultClient(**new_config["server"], **new_config["client"])
                  +    unwrap_client = vclient.VaultClient(
                  +        **new_config["server"],
                  +        **new_config["client"],
                  +        session=unwrap_client.session if unwrap_client is not None else None,
                  +    )
                       return new_config, embedded_token, unwrap_client


                  @@ -710,7 +713,7 @@

                           if result.get("wrap_info") or result.get("wrap_info_nested"):
                               if unwrap_client is None:
                  -                unwrap_client = vclient.VaultClient(**result["server"])
                  +                unwrap_client = vclient.VaultClient(**result["server"], **result.get("client", {}))

                               for key in [""] + result.get("wrap_info_nested", []):
                                   if key:
```
Unfortunately, after the change, it still went from 500 to the rendering exception message.
I noticed the salt-minions also have this file:
```
/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/vault/factory.py
```
Is it possible the that file is interferring with the saltext file somehow?

**Comment by callanova** [comment]
> The default is an ugly artifact of past days, disk would make much more sense here. Once we release a new major version, it's going to change.

Modified the vault config to the following:
```
peer_run:
  .*:
    - vault.get_config
    - vault.generate_secret_id

vault:
  auth:
    method: approle
    approle_mount: salt-minions
    approle_name: salt_master
    role_id: $REPLACEME
    secret_id: $REPLACEME
  cache:
    backend: disk
  issue:
    type: approle
    approle:
      mount: salt-minions
      params:
        token_num_uses: 0
        token_type: batch
  server:
    url: https://vault.company.com
    namespace: admin/
  client:
    max_retries: 10
    backoff_factor: 2.0
    retry_status:
      - 412
      - 500
      - 502
      - 503
      - 504
```
To make sure I understand, with this change, the creds are cached to the salt-minion and only reach out for new creds when the cache is expired?

> Which version is your Salt master?

On the salt master, I used the regular installation. It's version 3006.6.
When installing the saltext on the salt-minions, I used the state listed at https://salt-extensions.github.io/saltext-vault/topics/installation.html.

> Edit: Not sure if this makes a difference, but did you restart your minions after applying the patch?

I didn't. 

> This file only exists in Salt 3007.0

Looks like the salt minion got installed with version 3007:
```
salt-call --version
salt-call 3007.1 (Chlorine)
```
Downgraded the version to 3006:
```
salt-call --version
salt-call 3006.9 (Sulfur)
```
I restored `/opt/saltstack/salt/extras-3.10/saltext/vault/utils/vault/factory.py` to its original version on the salt-minions and ran sudo systemctl restart salt-minion.
I confirmed `/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/vault/factory.py` is no longer available.
I then ran sudo salt 'minion' vault.update_config given the above changes and let the automation run.

I still saw the 500 status code, so I applied the changes to the factory.py file again and ran sudo systemctl restart salt-minion.
After letting the automation run, the 500 status code still appears.

> But if your minions are on 3007+, you might want to check that they actually use the modules from this saltext, not the Salt core ones.

Given your call out and the information I provided above, I am wondering if they are actually using the saltext modules.
How can I check what module they are using?
sudo salt 'minion' sys.list_modules seems to only list the Salt core modules.
I'm not sure how to change this line to force the use of the saltext module:
```
{% set data = salt['vault.read_secret']('secrets/data/automation/saltstack/testing/ubuntu/data') %}
```

**Comment by lkubb** [comment]
> Modified the vault config to the following:

Note that it's missing `vault:client:retry_post`.

> To make sure I understand, with this change, the creds are cached to the salt-minion and only reach out for new creds when the cache is expired?

With this change, you get some form of persistency between runs. It caches the Vault server configuration for 1h (https://salt-extensions.github.io/saltext-vault/ref/configuration.html#config), after which it expires the cache and requests new configuration + creds (even if the latter are still valid). If the creds expire before the config cache, the minion just requests new creds (token/SecretID only, no config/RoleID).

It's also possible to never expire the config cache by setting `vault:cache:config` to `null`. Even with this value, changed `vault:server` config on the master is recognized and causes a config cache expiry on the minion. Other configuration changes, which would be picked up automatically after 1h at the latest by default, need a manual `vault.update_config`.

> On the salt master, I used the regular installation. It's version 3006.6.

OK, that explains the path.

> How can I check what module they are using?

It's much easier on 3006.x. If you downgraded your minion to 3006.9 and were still able to run `vault.update_config`, it must have used the saltext module, this function is not available on 3006.x.

> After letting the automation run, the 500 status code still appears.

If you applied the patch to the 3006.9 minion, restarted it, confirmed that `vault.update_config` ran successfully and the issue is still present, I can only explain it by the missing `retry_post` setting above.

Now that you have enabled a persistent cache, you can confirm that the minion has indeed received the correct configuration by taking a look at `/var/cache/salt/minion/vault/connection/config.p` (it's a msgpack-encoded file though, so you need some way of decoding it).

**Comment by callanova** [comment]
> Note that it's missing vault:client:retry_post.

My mistake, I deleted the line when pasting it here when redacting info. `retry_post` is set to true and in the vault config.
I ran sudo systemctl restart salt-master and I can confirm sudo salt 'minion' vault.update_config returns true.

> Now that you have enabled a persistent cache, you can confirm that the minion has indeed received the correct configuration by taking a look at /var/cache/salt/minion/vault/connection/config.p (it's a msgpack-encoded file though, so you need some way of decoding it).

On the salt-minion, `/var/cache/salt/minion/vault/connection/config.p` does exist.
Got it copied over to another machine and created a script to decode it.
The cache is set to disk:
```
'cache': {'backend': 'disk', 'clear_attempt_revocation': 60, 'clear_on_unauthorized': True, 'config': 3600, 'expire_events': False, 'kv_metadata': 'connection', 'secret': 'ttl'},
```
However, the client doesn't seem to respect retry_post:
```
'client': {'connect_timeout': 9.2, 'read_timeout': 30, 'max_retries': 5, 'backoff_factor': 0.1, 'backoff_max': 10.0, 'backoff_jitter': 0.2, 'retry_post': False, 'retry_status': [412, 500, 502, 503, 504], 'respect_retry_after': True, 'retry_after_max': 60},
```
I changed retry_post from `true` to `True` in the vault config, restarted the salt-master, and ran sudo salt 'minion' vault.update_config.
Copied `/var/cache/salt/minion/vault/connection/config.p` file to another machine. I then decoded the new version and confirmed it's still showing retry_post as `False`.
Just in case I've been looking at the terminal for too long, here's the config:
```
peer_run:
  .*:
    - vault.get_config
    - vault.generate_secret_id

vault:
  auth:
    method: approle
    approle_mount: salt-minions
    approle_name: salt_master
    role_id: $REPLACEME
    secret_id: $REPLACEME
  cache:
    backend: disk
  issue:
    type: approle
    approle:
      mount: salt-minions
      params:
        token_num_uses: 0
        token_type: batch
  server:
    url: https://vault.company.com
    namespace: admin/
  client:
    max_retries: 10
    backoff_factor: 2.0
    retry_post: True
    retry_status:
      - 412
      - 500
      - 502
      - 503
      - 504
```

**Comment by lkubb** [comment]
> However, the client doesn't seem to respect retry_post:

Yes, it seems all client options are set to their respective defaults. Weird.

Option 1: The master is sending the wrong data for some reason. To check, you can do the following:

On the master, run `salt-run state.event 'salt/run/*/ret' count=1 pretty=true`. In another session (or on the minion), run `salt minion vault.update_config` (`salt-call vault.update_config`). This should allow you to see the configuration the master distributes so you can check if it matches the expectation. [this assumes that no other runner return event happens in between, but you get the idea]

Option 2: You have set overrides for `vault:client` in the minion configuration. To check, run `salt minion config.get vault omit_pillar=true omit_master=true omit_grains=true`. The output should be empty.

Option 3: There's a bug I'm missing at the moment.

Side note: `true` vs `True` should not matter in YAML.

**Comment by callanova** [comment]
> Option 1: The master is sending the wrong data for some reason. To check, you can do the following:

Here's the output of `sudo salt-run state.event 'salt/run/*/ret' count=1 pretty=true`:
```
salt/run/20241106132556300000/ret       {
    "_stamp": "...",
    "fun": "runner.vault.get_config",
    "fun_args": [
        {
            "config_only": true,
            "impersonated_by_master": false,
            "issue_params": null,
            "minion_id": "...",
            "signature": "..."
        }
    ],
    "jid": "20241106132556300000",
    "return": {
        "auth": {
            "approle_mount": "salt-minions",
            "approle_name": "...",
            "method": "approle",
            "role_id": {
                "wrap_info": {
                    "creation_path": "auth/salt-minions/role/.../role-id",
                    "creation_time": 1730899556,
                    "token": "...",
                    "ttl": 30
                }
            },
            "secret_id": true,
            "token_lifecycle": {
                "minimum_ttl": 10,
                "renew_increment": null
            }
        },
        "cache": {
            "backend": "disk",
            "clear_attempt_revocation": 60,
            "clear_on_unauthorized": true,
            "config": 3600,
            "expire_events": false,
            "kv_metadata": "connection",
            "secret": "ttl"
        },
        "server": {
            "namespace": "admin/",
            "url": "https://vault.company.com",
            "verify": null
        },
        "wrap_info_nested": [
            "auth:role_id"
        ]
    },
    "success": true,
    "user": "salt"
}
```

> Option 2: You have set overrides for vault:client in the minion configuration.

Running `sudo salt 'minion' config.get vault omit_pillar=true omit_master=true omit_grains=true` shows an empty response:
```
minion:
```

Additional info just in case it's helpful, running `sudo find / -type f -name vault.py` shows:
```
/opt/saltstack/salt/extras-3.10/saltext/vault/runners/vault.py
/opt/saltstack/salt/extras-3.10/saltext/vault/pillar/vault.py
/opt/saltstack/salt/extras-3.10/saltext/vault/wrapper/vault.py
/opt/saltstack/salt/extras-3.10/saltext/vault/modules/vault.py
/opt/saltstack/salt/extras-3.10/saltext/vault/states/vault.py
/opt/saltstack/salt/extras-3.10/saltext/vault/sdb/vault.py
/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/vault.py
/opt/saltstack/salt/lib/python3.10/site-packages/salt/runners/vault.py
/opt/saltstack/salt/lib/python3.10/site-packages/salt/pillar/vault.py
/opt/saltstack/salt/lib/python3.10/site-packages/salt/modules/vault.py
/opt/saltstack/salt/lib/python3.10/site-packages/salt/states/vault.py
/opt/saltstack/salt/lib/python3.10/site-packages/salt/sdb/vault.py
```

**Comment by callanova** [comment]
On the salt-master, `sudo salt --versions-report`:
```
Salt Version:
          Salt: 3006.6

Python Version:
        Python: 3.10.12 (main, Sep 11 2024, 15:47:36) [GCC 11.4.0]

Dependency Versions:
          cffi: 1.17.1
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.0.3
       libgit2: Not Installed
  looseversion: 1.3.0
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.8
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 24.1
     pycparser: 2.22
      pycrypto: Not Installed
  pycryptodome: 3.20.0
        pygit2: Not Installed
  python-gnupg: Not Installed
        PyYAML: 5.4.1
         PyZMQ: 25.0.2
        relenv: Not Installed
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4

Salt Extensions:
 saltext.vault: 1.2.0

System Versions:
          dist: ubuntu 22.04.5 jammy
        locale: utf-8
       machine: x86_64
       release: 5.15.0-124-generic
        system: Linux
       version: Ubuntu 22.04.5 jammy

```

If I turn on debugging on the salt-master, it shows:
```
2024-11-06 14:54:54,986 [salt.loader.lazy :996 ][DEBUG   ][1599341] The functions from module 'vault' are being loaded by dir() on the loaded module
2024-11-06 14:54:54,986 [salt.utils.lazy  :98  ][DEBUG   ][1599341] LazyLoaded vault.get_config
```
I don't see any reference to loading saltext-vault.

**Comment by lkubb** [comment]
> I don't see any reference to loading saltext-vault.

I don't think the loader logs it that way, it would just show `vault` regardless of the source.

> If I run sudo salt 'minion' pip.list it shows saltext.vault at version 1.2.0.

Yes, in light of the master not distributing `client`, your cached config suggests that.

> `sudo salt --versions-report`

If this output is correct, there's definitely something off about your Salt master installation. 3006.6 by itself does not have a `vault.get_config` runner, it can only be provided by the listed `saltext-vault`, but version `1.2.0` would definitely include `client` in the return.

You noted that you restarted the master during testing this, so the running daemon's version should match what is reported here. We might need to do some nitpicking to find the cause.

The output suggests the `salt` command executed by `sudo salt --versions-report` is at version 3006.6. Is it using the same Python environment as your running master daemon? I'm not sure how your master is installed since you said you didn't perform a onedir installation from the official repos.

By default, the systemd service should be discoverable at `/etc/systemd/system/multi-user.target.wants/salt-master.service`. Its default `ExecStart` is `/usr/bin/salt-master`, but better check which command the service actually executes. Then use this command together with `--versions-report`, so usually `/usr/bin/salt-master --versions-report`.

**Comment by callanova** [comment]
Okay, there's a bit to unpack here. I want to start off by saying **thank you for your help and patience with this**.

First, you are right, when the salt-master was installed originally it wasn't with the onedir version.
You caught it with pointing out using `/usr/bin/salt-master --versions-report`. It was showing 3007.1.
I pinned the version to 3006 by creating `/etc/apt/preferences.d/salt-pin-1001` as mentioned in https://docs.saltproject.io/salt/install-guide/en/latest/topics/install-by-operating-system/linux-deb.html and then downgraded the package.
`sudo salt --versions` was still showing the saltext.vault being installed but, `sudo salt 'minion' vault.update_config` was resulting in `"'vault.get_config' is not available."`
However, `/usr/bin/salt-master --versions-report` wasn't showing the saltext.vault as installed.
I attempted to run salt-pip install saltext-vault but that resulted in this message:
```
'salt-pip' is only meant to be used from a Salt onedir. You probably want to use the system 'pip` binary.
```
Given this wasn't originally installed using the original onedir method, `which -a salt` showed three entries:
```
/usr/local/bin/salt
/usr/bin/salt
/bin/salt
```
`/usr/local/bin/salt` was the outdated entry.
After removing all the salt entries from /usr/local/bin/, salt-pip was able to install the saltext-vault and `sudo salt --versions-report` shows:
```
Salt Version:
          Salt: 3006.9

Python Version:
        Python: 3.10.14 (main, Jun 26 2024, 11:44:37) [GCC 11.2.0]

Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
  cryptography: 42.0.5
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.4
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.19.1
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 6.0.1
         PyZMQ: 23.2.0
        relenv: 0.17.0
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4

Salt Extensions:
 saltext.vault: 1.2.0

System Versions:
          dist: ubuntu 22.04.5 jammy
        locale: utf-8
       machine: x86_64
       release: 5.15.0-124-generic
        system: Linux
       version: Ubuntu 22.04.5 jammy
```
`sudo salt 'minion' vault.update_config` was able to work successfully and `sudo salt-run state.event 'salt/run/*/ret' count=1 pretty=true` shows the client section:
```
...
        "client": {
            "backoff_factor": 2.0,
            "backoff_jitter": 0.2,
            "backoff_max": 10.0,
            "connect_timeout": 9.2,
            "max_retries": 10,
            "read_timeout": 30,
            "respect_retry_after": true,
            "retry_after_max": 60,
            "retry_post": true,
            "retry_status": [
                412,
                500,
                502,
                503,
                504
            ]
        },
...
None
```
I let the automation run for a bit more time but, we would still go from the 500 status code to the rendering exception message.
That was without any changes to factory.py.
I applied the recommended changes from https://github.com/salt-extensions/saltext-vault/issues/95#issuecomment-2455922342 and let the automation run again.

After waiting for a 500 status code, I was able to catch this:
```
2024-11-06 18:28:18,422 [urllib3.connectionpool:1019][DEBUG   ][36791] Starting new HTTPS connection (1): vault.company.com:443
2024-11-06 18:28:18,444 [urllib3.connectionpool:474 ][DEBUG   ][36791] https://vault.company.com:443 "POST /v1/sys/wrapping/lookup HTTP/1.1" 500 136
2024-11-06 18:28:18,444 [urllib3.util.retry:594 ][DEBUG   ][36791] Incremented Retry for (url='/v1/sys/wrapping/lookup'): VaultRetry(total=9, connect=None, read=None, redirect=None, status=None)
2024-11-06 18:28:22,348 [salt.minion      :892 ][DEBUG   ][35108] Minion return retry timer set to 9 seconds (randomized)
2024-11-06 18:28:22,562 [urllib3.connectionpool:893 ][DEBUG   ][36791] Retry: /v1/sys/wrapping/lookup
2024-11-06 18:28:22,572 [urllib3.connectionpool:474 ][DEBUG   ][36791] https://vault.company.com:443 "POST /v1/sys/wrapping/lookup HTTP/1.1" 200 316
2024-11-06 18:28:22,667 [urllib3.connectionpool:474 ][DEBUG   ][36791] https://vault.company.com:443 "POST /v1/sys/wrapping/unwrap HTTP/1.1" 200 334
2024-11-06 18:28:22,668 [saltext.vault.utils.vault.auth:133 ][DEBUG   ][36791] Vault token expired. Recreating one by authenticating with AppRole.
2024-11-06 18:28:22,781 [urllib3.connectionpool:474 ][DEBUG   ][36791] https://vault.company.com:443 "POST /v1/auth/salt-minions/login HTTP/1.1" 200 1215
```
It looks like the patch you mentioned previously does mitigate the behavior.

**Comment by lkubb** [comment]
Well, that certainly felt like a rollercoaster! Glad we could solve this issue.

> It looks like the patch you mentioned previously does mitigate the behavior.

Funny how it wasn't even the root cause of you posting this issue, but turned out to be a valid one nonetheless. I was quite certain twice we had found the cause (enabling `retry_post`, the patch) because it fit so well.

Thanks a lot for following up and testing the patch, I will include it here and do a new patch release.

You might want to play with the `cache:config` value and `issue:approle:params:[token_excplicit_max_ttl|token_ttl]`or `issue:approle:params:secret_id_num_uses]` if the load on the master/Vault cluster is too high. With your current configuration, a minion needs to request a new SecretID each time it wants to authenticate, which grants it a token that lasts for 60s (it's 4 API requests per cycle: 1. master issues SecretID 2. minion looks up wrapping token info 3. minion unwraps SecretID 4. minion logs in with new SecretID).

Final note regarding your config since I'm not sure you noticed it when I highlighted it earlier:

It's a bad idea to use the same mount for the Salt master AppRole and the one the master manages for minion AppRoles (some code might assume it's exclusively dedicated to minion AppRoles, at least `salt-run vault.cleanup_auth` does, unsure if there are other places off the top of my head).

Wishing you a path forward devoid of issues after this odyssey. :)

**Comment by callanova** [comment]
> Final note regarding your config since I'm not sure you noticed it when I highlighted it earlier:

Salt master was approle_mount has now been changed to `approle`.

The salt-minions and salt-master now have v1.2.1 from https://github.com/salt-extensions/saltext-vault/pull/98 installed and I can see the retry working.
Thank you again for all your help and insight! This extension is awesome.
